ice_breaker:
    excellent:
    above_average:
    good:
    needs_improvement:
    non-existent:
worship:
    excellent:
    above_average:
    good:
    needs_improvement:
    non-existent:
edification:
    excellent:
    above_average:
    good:
    needs_improvement:
    non-existent:
vision:
    excellent:
    above_average:
    good:
    needs_improvement:
    non-existent:
fellowship:
    excellent:
    above_average:
    good:
    needs_improvement:
    non-existent:
